[package]
name = "atomcrypte"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
blake3 = "1.8"
rayon = "1"
subtle = "2.6"
thiserror = "2.0"
num_cpus = "1"
argon2 = "0.5"
zeroize = "1.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1